apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: present
spec:
  rules:
  - host: present.r15cookie.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: present
            port: 
              number: 1948
  tls:
  - hosts:
    - present.r15cookie.com
    secretName: present-cert
status:
  loadBalancer: {}
