apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-intro-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: present
          servicePort: 1948
        path: /
  tls:
  - hosts:
    - present.r15cookie.com
    secretName: present-tls
status:
  loadBalancer: {}
