apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: present-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: present
          servicePort: 1948
        path: /
status:
  loadBalancer: {}
